server:
  port: 8762

  servlet:
    context-path: /grocerysearchservice

spring:
  application:
    name: grocerysearchservice

  datasource:
    url: jdbc:postgresql://localhost:5433/search_db
    username: search_user
    password: search_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

springdoc:

  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    try-it-out-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always

info:
  app:
    name: Grocery Search Service
    version: 1.0.0
    description: Production Ready Grocery Search Service

#eureka:
  #client:
    #service-url:
      #defaultZone: http://admin:admin123@localhost:8761/eureka/